In [52]:
import dotenv

import rasterio
import geopandas as gpd
import numpy as np
import pandas as pd
import rasterstats

from rasterstats import zonal_stats
from rasterio.warp import reproject, Resampling, calculate_default_transform
from rasterio.mask import mask

from food_security import salinity_correction, water_quality

from pathlib import Path

In [2]:
config = dotenv.dotenv_values(".env")
username = config["FAOSTAT_USERNAME"]
password = config["FAOSTAT_PASSWORD"]

In [3]:
src_dir = Path('~').expanduser() / "OneDrive - Stichting Deltares/Tiaravanni Hermawan's files - Egypt/04_Data/2026_data/"

In [4]:
toml_file = src_dir.parent / "salinity_correction_egypt.toml"
# corrected_df = salinity_correction.generate_crop_yield_csv(
#     config_path=toml_file,
#     add_labor=True,
#     save=False,
#     username=username,
#     password=password,
# )

In [5]:
corrected_df

,area_map_name,crop_name,crop_name_fao,salinity,yield,hectares,year,a,b,corrected_yield,corrected_yield_pp,comment,FTE
2073,أبو المنجا,Orchard_CITRUS1 (ha),Lemons and limes,0.116154,0.0,872.783691,2021,1.5,12.8,0.0,0.000000e+00,nan,0.000000
2013,أبو المنجا,SummerMaize_MAIZES1 (ha),Maize (incl. 0067 and 0068),0.117790,0.0,323.750214,2021,1.7,12.0,0.0,0.000000e+00,nan,0.000000
1533,أبو المنجا,Soybean_SBEAN1 (ha),Soybeans,0.000000,5713.539062,0.0,2020,5.0,20.0,5713.539062,4.443038e+03,nan,2.354480
3693,أبو المنجا,Flax_FLAX1 (ha),Linseed,0.000000,0.0,0.0,2021,1.7,12.0,0.0,0.000000e+00,nan,0.000000
3633,أبو المنجا,SummerOnion_ONIONS1 (ha),"Tomatoes, fresh",0.116104,0.0,9.638799,2021,2.5,9.9,0.0,0.000000e+00,nan,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3543,نجع حمادى الغربية,LongRice_PADDY1 (ha),"Rice, paddy",0.111464,0.0,92.270279,2021,3.0,12.0,0.0,0.000000e+00,nan,0.000000
2043,نجع حمادى الغربية,Orchard_CITRUS1 (ha),Lemons and limes,1.851262,0.0,621.844482,2021,1.5,12.8,0.0,0.000000e+00,nan,0.000000
303,نجع حمادى الغربية,SugarCane_SCANE1 (ha),Sugar cane,1.841218,547593728.0,5008.95459,2020,1.7,5.9,547591808.0,2.166639e+07,nan,175510.194872
183,نجع حمادى الغربية,Orchard_CITRUS1 (ha),Lemons and limes,1.841218,13949838.0,621.844482,2020,1.5,12.8,13910592.0,5.312455e+06,nan,191.079560
1863,نجع حمادى الغربية,Bean_FBEAN1 (ha),"Beans, dry",1.818808,172332.59375,49.677891,2021,1.0,19.0,157783.96875,1.745564e+05,nan,166.164436

In [6]:
excel_salinity_df = pd.DataFrame(
    {
        "crop_name": corrected_df["crop_name"],
        "crop_name_fao": corrected_df["crop_name_fao"],
        "area": corrected_df["area_map_name"],
        "yield": corrected_df["corrected_yield"],
        "year": corrected_df["year"],
    }
)

excel_drought_df = pd.DataFrame(
    {
        "crop_name": corrected_df["crop_name"],
        "crop_name_fao": corrected_df["crop_name_fao"],
        "area": corrected_df["area_map_name"],
        "yield": corrected_df["yield"],
        "year": corrected_df["year"],
    }
)

excel_salinity_df["scenario"] = None
excel_drought_df["scenario"] = None

In [5]:
water_prod_df, water_use_df = water_quality.generate_water_csv(
    config_path=toml_file,
    # corrected_df=corrected_df,
    save=True,
    username=username,
    password=password,
)

5 / Blk_Air_20

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

9 / Blk_Air_24
10 / Blk_Air_23

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

14 / Blk_Air_9
16 / Blk_Air_22

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

19 / Blk_Air_21
25 / Blk_Air_26

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

27 / Blk_Air_6
28 / Blk_Air_25

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

33 / Blk_Air_7
35 / Blk_Air_8

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

41 / Blk_Air_65
42 / Blk_Air_62

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

44 / Blk_Air_27
47 / Blk_Air_11

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

51 / Blk_Air_77

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

61 / Blk_Air_58
62 / Blk_Air_59

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

64 / Blk_Air_60
81 / Blk_Air_41

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

89 / Blk_Air_39
91 / Blk_Air_40

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

92 / Blk_Air_52
96 / Blk_Air_2

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

108 / Blk_Air_53
114 / Blk_Air_NewDevelopment_ElDab3a

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

120 / Blk_Air_1
124 / Blk_Air_47

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

126 / Blk_Air_46
128 / Blk_Air_43

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

130 / Blk_Air_44
132 / Blk_Air_45

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

133 / Blk_Air_42
140 / Blk_Air_NewDevelopment_42
147 / Blk_Air_38

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

148 / Blk_Air_16
153 / Blk_Air_48

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

154 / Blk_Air_37
156 / Blk_Air_19

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

158 / Blk_Air_17
164 / Blk_Air_50

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

166 / Blk_Air_49
168 / Blk_Air_12

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

169 / Blk_Air_51
172 / Blk_Air_34

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

173 / Blk_Air_63
175 / Blk_Air_14

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

195 / Blk_Air_13
197 / Blk_Air_36

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

200 / Blk_Air_57
201 / Blk_Air_35

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

204 / Blk_Air_18
205 / Blk_Air_30

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

211 / Blk_Air_28
212 / Blk_Air_29

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

213 / Blk_Air_55
215 / Blk_Air_54

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

216 / Blk_Air_33
220 / Blk_Air_15

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

222 / Blk_Air_32
224 / Blk_Air_31

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

226 / Blk_Air_56
233 / Blk_Air_Reuse_65

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

283 / Blk_Air_78
1136 / Blk_Air_Reuse_62

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

1140 / Blk_Air_Reuse_60
1143 / Blk_Air_Reuse_59

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

1147 / Blk_Air_Reuse_2

/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/Users/hemert/projects/food-security/Food-Security/.venv/lib/python3.12/site-packages/numpy/lib/_nanfunctions_impl.py:1213: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [21]:
excel_water_prod_df = pd.DataFrame(
    {
        "area": water_prod_df["area_map_name"],
        "year": water_prod_df["year"],
        "water_productivity": water_prod_df["water_productivity"],
        "hectares": water_prod_df["hectares"],
    }
)

excel_water_use_df = pd.DataFrame(
    {
        "area": water_use_df["area_map_name"],
        "year": water_use_df["year"],
        "timestep": water_use_df["timestep"],
        "water_use": water_use_df["water_use"],
        "water_exploitation_index": water_use_df["water_exploitation_index"],
        "hectares": water_use_df["hectares"],
    }
)

In [22]:
# excel_path = src_dir / "input_test_egypt.xlsx"
# write_dir = pathlib.Path("/Users/hemert/OneDrive - Stichting Deltares/Documents - International Delta Toolset/Salinity/Vietnam/")
# excel_path = write_dir / 'input.xlsx'
excel_path = "/Users/hemert/OneDrive - Stichting Deltares/Tiaravanni Hermawan's files - Egypt_ERF_data/data_correlation.xlsx"

def write_excel_file(df, excel_path, sheet_name, append=False):
    # Open Excel file
    try:
        # book = load_workbook(excel_path)
        with pd.ExcelWriter(
            excel_path, engine="openpyxl", mode="a", if_sheet_exists="replace"
        ) as writer:
            # excel_file.book = book
            df.to_excel(writer, sheet_name=sheet_name, index=False)
    except Exception as e:
        print(e)
        df.to_excel(excel_path, sheet_name=sheet_name, index=False)

write_excel_file(excel_water_prod_df, excel_path, sheet_name="water_productivity")
write_excel_file(excel_water_use_df, excel_path, sheet_name="water_use")

In [58]:
def count_per_type(x, field_type):
    x = x[x == field_type]
    return np.ma.count(x)


def read_field_sizes(tif_file, area_gdf):
    with rasterio.open(tif_file) as src:
        stats = rasterstats.zonal_stats(
            area_gdf,
            tif_file,
            stats="count",
            add_stats={
                "count_0": lambda x: count_per_type(x, 0),
                "count_1": lambda x: count_per_type(x, 3502),
                "count_2": lambda x: count_per_type(x, 3503),
                "count_3": lambda x: count_per_type(x, 3504),
                "count_4": lambda x: count_per_type(x, 3505),
                "count_5": lambda x: count_per_type(x, 3506),
            },
            nodata=src.nodata,
        )

    return stats


def create_stats_df(stats, area_gdf):
    df_dict = {
        "area": area_gdf["NAME1_"].values,
        "nr_of_fields": [s["count"] for s in stats],
        "nr_no_field": [s["count_0"] for s in stats],
        "nr_<0.64ha": [s["count_5"] for s in stats],
        "nr_0.64-2.56ha": [s["count_4"] for s in stats],
        "nr_2.56-16ha": [s["count_3"] for s in stats],
        "nr_16-100ha": [s["count_2"] for s in stats],
        "nr_>100ha": [s["count_1"] for s in stats],
    }
    df = pd.DataFrame(df_dict)
    return df


def compute_fraction(df, field):
    total = df["nr_of_fields"]
    value = df[f"nr_{field}"]

    df[f"fraction_{field}"] = value / total
    return df

In [27]:
field_type_file = src_dir / "dominant_field_size_categories.tif"

com_gdf = gpd.read_file(src_dir / 'Final2_Command_Area.shp')
com_gdf = com_gdf.to_crs("EPSG:4326")

field_stats = read_field_sizes(field_type_file, com_gdf)

field_size_df = create_stats_df(stats=field_stats, area_gdf=com_gdf)
field_size_df['fraction_small'] = (field_size_df['nr_<0.64ha']) / field_size_df['nr_of_fields']
field_size_df['fraction_medium'] = (field_size_df['nr_0.64-2.56ha']) / field_size_df['nr_of_fields']
field_size_df['fraction_large'] = (field_size_df['nr_2.56-16ha']) / field_size_df['nr_of_fields']

write_excel_file(field_size_df, excel_path, sheet_name="field_sizes")

In [28]:
livestock_files = [
    src_dir / "glw_cattle_v3.tif",
    src_dir / "glw_chicken_v3.tif",
    src_dir / "glw_goats_v3.tif",
    src_dir / "glw_sheeps_v3.tif"
]



livestock_df = pd.DataFrame(
    {
        "area": com_gdf["Name"]
    }
)

for livestock_file in livestock_files:
    col = livestock_file.stem
    livestock_type = col.split("_")[1]
    with rasterio.open(livestock_file) as livestock_src:
        stats = zonal_stats(
            com_gdf,
            livestock_file,
            affine=livestock_src.transform,
            stats=["sum"],
            nodata=livestock_src.nodata,
        )

    livestock_df[livestock_type] = [s["sum"] for s in stats]

write_excel_file(livestock_df, excel_path, sheet_name="livestock")

In [16]:
livestock_df

,area,cattle,chicken,goats,sheeps
0,الرشيدية_ومباشر غرب رشيد,22727.055179,5.587898e+05,16775.364086,25664.208919
1,الرياح البحيرى,198124.211802,3.887026e+06,82419.528990,138343.372796
2,الخيام,47397.003046,9.870618e+05,49871.778378,49926.848211
3,نجع حمادى الغربية,313646.891766,7.690724e+06,356662.149606,371249.818055
4,نجع حمادى الشرقية,78113.741969,2.139384e+06,98249.213915,98097.195372
5,الكلابية,102254.195186,1.237642e+06,126324.398730,157353.194044
6,ترعة الصف,14354.250245,1.460087e+06,16955.254650,24511.769499
7,البحر الصغير,43911.916374,3.095713e+06,13097.626724,35743.283905
8,النجايل,25824.585428,6.366150e+05,11853.549239,18144.670091
9,قنال العنانية,10230.916625,2.086722e+05,1636.473826,2638.816982
10,البلامون _ الساحل,46937.448871,2.095342e+06,10371.703477,24492.898264
11,الشرقاوية,72968.578074,2.314517e+06,38836.265277,43716.389912
12,البوهية,32890.849907,2.155508e+06,9899.333528,25894.087736
13,بحر شبين,225464.581331,5.508755e+06,92196.037340,155772.384517
14,بحر مويس,259045.458326,8.868499e+06,134547.035007,156670.980883
15,أسوان,21005.613737,1.323577e+06,20733.093469,27987.594885
16,الرنان الرئيسي,16189.732206,2.971258e+05,27229.856756,33326.183147
17,زمام اصفون,53356.911084,6.045208e+05,53866.152298,95276.551124
18,زمام الرمادي,24670.427815,3.720736e+05,44379.493603,39993.039469
19,زمام الكلابية القديمة,NaN,NaN,NaN,NaN
20,ابوحمار,9743.126734,1.538016e+05,11433.200042,14387.651702
21,الرنان الشرقي_بخانس,22007.304416,3.336219e+05,32307.137278,34654.631455
22,مباشر نيل,6624.311683,3.470708e+05,15252.966053,14630.803371
23,عمر بك,18577.924041,6.002502e+05,9106.951099,13855.586922
24,جنابية دهتورة,NaN,NaN,NaN,NaN
25,العطف,86501.797572,2.040639e+06,38270.351324,57942.534654
26,البحر الصعيدي,12805.378589,2.885325e+05,6064.472917,8514.824594
27,خليج القني,4403.010700,2.376589e+05,2353.878985,4148.124366
28,بحر بسنديلة _ بلقاس _ تيرة,118773.123965,3.286388e+06,38542.475048,89426.775700
29,السلام,27858.692752,4.947596e+05,26902.125176,39056.301120
30,الباجورية,81629.768573,2.620946e+06,26753.707597,53898.152169
31,دروة وراضى,NaN,NaN,NaN,NaN
32,الباسوسية,76837.029091,2.032565e+06,35424.903444,42983.608612
33,أبو المنجا,77068.683889,2.278527e+06,37933.635402,48219.517093
34,ترعة البستان,15947.492269,7.005836e+04,23797.653018,49700.578606
35,ترعة النصر,36593.255993,3.982419e+05,53923.788666,120109.807155
36,الرياح الناصرى,23614.367453,6.077929e+05,24705.430898,51288.494048
37,ترعة سيناء,6547.559741,6.061301e+04,4322.623148,3476.292800
38,ترعة المنايف,7770.919087,4.389396e+05,6761.046351,8066.815841
39,ترعة بورسعيد,3097.266957,1.486989e+05,2680.810171,3349.678481
40,ترعة السويس,5477.163928,2.715640e+05,4960.464737,5823.796488
41,ترعي الصالحية و السعيدية,65453.375235,2.230042e+06,57536.092590,78848.939344
42,ترعة الإسماعيلية,70321.824442,2.929204e+06,56481.303808,84393.290163
43,الرياح التوفيقى,36159.883104,2.103273e+06,12429.073030,26604.240194
44,بحر طناح,11894.290716,7.657004e+05,3546.254934,9352.071138
45,المنصورية,23291.413443,1.026822e+06,10125.383514,17265.995121
46,الشرقاوية_ من المنصورية,28041.550806,8.022380e+05,4132.044345,9232.282151
47,النوبارية,197602.282688,3.189509e+06,127800.667059,254995.799798
48,المحمودية,117500.761157,2.269812e+06,75061.122311,97218.769354
49,ميت يزيد,107877.554683,3.063038e+06,39221.326787,77076.122591
50,الرياح العباسى,41237.248691,1.374279e+06,16861.574517,31902.854984
51,زمام الرشدية_وسط الدلتا,8644.803766,3.402780e+05,4644.338865,8112.880795
52,الرياح المنوفى,132357.369853,2.819531e+06,52555.610595,90029.849946
53,الابراهيمية,331682.102362,9.728607e+06,338242.769938,323804.465670
54,بحر حسن واصف,77288.367728,2.415444e+06,43794.014931,61972.221458
55,البحر اليوسفي_الفيوم,110169.584337,4.802102e+06,66434.392812,88591.576289
56,ترعة سري باشا,29870.634995,8.747634e+05,34104.924020,34986.027537
57,ترعة الشيخ جابر,6065.290912,1.670963e+05,5394.566392,3315.692299
58,البحر اليوسفي,77010.312115,1.999199e+06,108474.536416,116533.661405
59,ترعة الجيزة,17578.133675,1.784073e+06,14898.744268,21051.674946

In [40]:
drains_gdf = gpd.read_file(src_dir / 'drains_small.shp')
canals_gdf = gpd.read_file(src_dir / 'MWRI_canals_wgs84_edit28062021.shp')

In [41]:
com_gdf_ecrs = com_gdf.to_crs(drains_gdf.crs)
canals_gdf = canals_gdf.to_crs(drains_gdf.crs)

In [39]:
com_gdf_ecrs['drain_length'] = 0
com_gdf_ecrs['canal_length'] = 0

In [42]:
for i, row in com_gdf_ecrs.iterrows():
    area_polygon = row['geometry']
    
    drains = drains_gdf.intersection(area_polygon)
    drain_length = drains.length.sum()
    com_gdf_ecrs.loc[i, 'drain_length'] = drain_length

    canals = canals_gdf.intersection(area_polygon)
    canal_length = canals.length.sum()
    com_gdf_ecrs.loc[i, 'canal_length'] = canal_length

In [43]:
com_gdf_ecrs

,OBJECTID,Name,Shape_Leng,Shape_Area,Feddan,geometry,drain_length,canal_length
0,1,الرشيدية_ومباشر غرب رشيد,121389.174241,3.754359e+08,89389.50,"POLYGON ((247461.461 3475172.069, 247509.794 3...",2.306789e+05,2.614794e+05
1,2,الرياح البحيرى,379980.523243,1.387385e+09,330330.00,"POLYGON ((261305.4 3444700.118, 263931.396 344...",7.283557e+05,1.046353e+06
2,6,الخيام,164484.927752,2.457438e+08,58510.40,"POLYGON ((406128.564 2896644.369, 405851.638 2...",7.127981e+04,1.823682e+05
3,7,نجع حمادى الغربية,541735.552974,1.950372e+09,464374.00,"MULTIPOLYGON (((413357.904 2888052.363, 413605...",7.486929e+05,3.095325e+06
4,8,نجع حمادى الشرقية,385861.370984,6.143672e+08,146278.00,"POLYGON ((302966.787 3027653.613, 303344.583 3...",1.811085e+05,8.349517e+05
5,9,الكلابية,334344.834772,7.479556e+08,178085.00,"POLYGON ((431202.296 2887164.225, 431117.995 2...",2.929709e+05,3.069003e+05
6,11,ترعة الصف,247397.493839,4.899687e+08,116659.00,"POLYGON ((335563.849 3315535.74, 335849.138 33...",1.571066e+05,2.437551e+05
7,12,البحر الصغير,169102.077473,6.934083e+08,165097.00,"MULTIPOLYGON (((373025.884 3453005.123, 372789...",4.754540e+05,6.069396e+05
8,13,النجايل,89164.070500,1.617347e+08,38508.30,"POLYGON ((312678.401 3354891.789, 312809.524 3...",8.207421e+04,1.934281e+05
9,14,قنال العنانية,69567.786666,6.687478e+07,15922.60,"MULTIPOLYGON (((383065.59 3474016.918, 383059....",2.048377e+04,4.841041e+04
10,15,البلامون _ الساحل,248901.403537,5.682803e+08,135305.00,"POLYGON ((386115.99 3482536.547, 386148.309 34...",3.387541e+05,4.100188e+05
11,16,الشرقاوية,120670.195430,5.983739e+08,142470.00,"POLYGON ((366071.285 3381144.934, 366282.478 3...",3.616606e+05,5.702422e+05
12,17,البوهية,128027.331374,5.657738e+08,134708.00,"POLYGON ((353746.254 3404746.707, 353734.769 3...",3.687785e+05,5.390473e+05
13,18,بحر شبين,227695.614642,1.304927e+09,310697.00,"POLYGON ((324537.58 3400477.69, 324535.647 340...",6.603807e+05,1.168244e+06
14,19,بحر مويس,281979.844735,1.843466e+09,438920.00,"MULTIPOLYGON (((365751.204 3381188.31, 365794....",1.060564e+06,1.842766e+06
15,20,أسوان,755358.494757,1.448439e+09,344866.00,"MULTIPOLYGON (((492596.042 2736638.363, 492483...",8.308817e+05,9.663322e+05
16,21,الرنان الرئيسي,109003.972620,1.746415e+08,41581.30,"POLYGON ((449235.97 2888149.814, 449512.191 28...",6.097207e+04,2.543560e+05
17,22,زمام اصفون,242292.235317,3.246991e+08,77309.30,"POLYGON ((464898.564 2895094.495, 465541.001 2...",1.249966e+05,5.904975e+05
18,23,زمام الرمادي,103284.777776,2.262998e+08,53880.90,"POLYGON ((448406.176 2818526.454, 450178.181 2...",9.697741e+04,3.042340e+05
19,24,زمام الكلابية القديمة,45239.055900,4.359444e+07,10379.60,"POLYGON ((457207.751 2806899.363, 457680.143 2...",5.111187e+03,7.175690e+04
20,25,ابوحمار,35283.229044,5.976739e+07,14230.30,"POLYGON ((414225.794 2894767.513, 414503.784 2...",4.086845e+04,9.276093e+04
21,26,الرنان الشرقي_بخانس,71339.871393,1.535572e+08,36561.20,"POLYGON ((405739.535 2892878.328, 409051.672 2...",1.102801e+05,1.979496e+05
22,27,مباشر نيل,440607.015302,2.347692e+08,55897.40,"MULTIPOLYGON (((291437.212 3034232.687, 291597...",1.332338e+04,1.008104e+05
23,28,عمر بك,71886.744291,1.007574e+08,23989.90,"POLYGON ((329810.435 3413326.214, 329709.721 3...",5.163853e+04,7.928042e+04
24,29,جنابية دهتورة,19519.801737,1.079042e+07,2569.15,"POLYGON ((329688.363 3409786.849, 329770.851 3...",5.419485e+02,9.749940e+03
25,30,العطف,116190.657305,4.933201e+08,117457.00,"POLYGON ((327884.628 3403887.751, 327862.134 3...",1.989802e+05,4.090006e+05
26,31,البحر الصعيدي,69542.655002,1.913176e+08,45551.80,"POLYGON ((278477.706 3476569.989, 279204.884 3...",1.197070e+05,1.534176e+05
27,32,خليج القني,20435.139266,1.820244e+07,4333.91,"POLYGON ((267968.206 3464105.828, 267225.448 3...",1.356750e+04,1.119796e+04
28,33,بحر بسنديلة _ بلقاس _ تيرة,236771.991064,1.818626e+09,433006.00,"POLYGON ((348015.766 3445182.571, 346283.173 3...",9.922790e+05,1.203083e+06
29,34,السلام,304083.244938,9.971843e+08,237425.00,"POLYGON ((385630.636 3461552.036, 385699.215 3...",5.493814e+05,6.011179e+05
30,35,الباجورية,228446.895459,8.882516e+08,211488.00,"POLYGON ((301050.154 3441198.918, 301042.472 3...",5.133518e+05,6.452880e+05
31,36,دروة وراضى,72970.788021,5.093019e+07,12126.20,"POLYGON ((317309.237 3362004.576, 317181.238 3...",0.000000e+00,4.798404e+04
32,37,الباسوسية,127801.857000,2.623758e+08,62470.40,"POLYGON ((340977.722 3372124.817, 340818.47 33...",1.293123e+05,2.917727e+05
33,38,أبو المنجا,110830.420956,2.991833e+08,71234.10,"MULTIPOLYGON (((318811.258 3355268.666, 318841...",1.683022e+05,2.979152e+05
34,39,ترعة البستان,132924.732070,8.413742e+08,200327.00,"POLYGON ((248448.193 3389335.215, 255392.717 3...",1.048456e+05,4.089392e+05
35,40,ترعة النصر,348502.131941,1.466091e+09,349069.00,"POLYGON ((185079.349 3415857.799, 185322.453 3...",5.332016e+05,6.324299e+05
36,41,الرياح الناصرى,189154.586343,4.032182e+08,96004.30,"POLYGON ((277734.729 3399157.703, 277806.622 3...",4.517861e+04,1.625571e+05
37,42,ترعة سيناء,228408.192093,6.009114e+08,143074.00,"POLYGON ((435479.997 3382978.703, 437861.242 3...",5.403533e+04,1.121261e+05
38,43,ترعة المنايف,81242.775718,3.968343e+08,94484.30,"POLYGON ((421639.261 3382028.621, 422560.183 3...",3.430424e+04,5.361373e+04
39,44,ترعة بورسعيد,158218.180406,1.998280e+08,47578.10,"POLYGON ((433979.697 3432445.521, 433993.228 3...",5.515586e+04,6.276536e+04
40,45,ترعة السويس,241200.663414,4.279141e+08,101884.00,"POLYGON ((431397.237 3380300.648, 431749.085 3...",1.257825e+05,1.201126e+05
41,46,ترعي الصالحية و السعيدية,177227.006184,1.058180e+09,251948.00,"POLYGON ((416589.568 3414629.024, 416213.503 3...",2.434151e+05,3.943829e+05
42,47,ترعة الإسماعيلية,358672.555488,1.657309e+09,394597.00,"POLYGON ((378844.659 3395435.159, 378809.101 3...",2.508416e+05,5.764692e+05
43,48,الرياح التوفيقى,181335.427857,5.172151e+08,123146.00,"POLYGON ((341863.199 3416750.02, 341885.557 34...",3.046970e+05,4.712147e+05
44,49,بحر طناح,116242.118633,3.425843e+08,81567.70,"POLYGON ((395010.736 3438389.663, 394891.563 3...",2.454156e+05,3.132129e+05
45,50,المنصورية,86295.515439,2.406144e+08,57289.10,"POLYGON ((348781.653 3438300.083, 348803.948 3...",1.137620e+05,2.028427e+05
46,51,الشرقاوية_ من المنصورية,146848.436093,2.840497e+08,67630.90,"POLYGON ((382499.346 3473644.792, 382545.347 3...",1.853191e+05,3.070254e+05
47,52,النوبارية,540522.768222,2.392990e+09,569759.00,"POLYGON ((202178.986 3439834.329, 202238.072 3...",1.228173e+06,1.219739e+06
48,53,المحمودية,258304.418666,1.203503e+09,286548.00,"POLYGON ((219560.05 3465964.289, 219401.683 34...",7.818878e+05,7.013232e+05
49,54,ميت يزيد,204307.451596,1.118941e+09,266414.00,"POLYGON ((306666.926 3482380.726, 306713.391 3...",6.210549e+05,6.288738e+05
50,55,الرياح العباسى,171993.414128,5.345701e+08,127279.00,"POLYGON ((347905.081 3444435.111, 347813.043 3...",2.839172e+05,4.231272e+05
51,56,زمام الرشدية_وسط الدلتا,110445.263979,2.196591e+08,52299.80,"MULTIPOLYGON (((253413.057 3484838.777, 255583...",1.232592e+05,1.550924e+05
52,57,الرياح المنوفى,217246.533904,7.091952e+08,168856.00,"POLYGON ((293887.15 3410787.647, 293661.505 34...",3.873636e+05,7.348452e+05
53,58,الابراهيمية,862976.326243,2.632504e+09,626787.00,"POLYGON ((276004.137 3085665.058, 276561.268 3...",1.799277e+06,3.440579e+06
54,59,بحر حسن واصف,431221.584178,7.670328e+08,182627.00,"MULTIPOLYGON (((257753.649 3232051.906, 257588...",3.893471e+05,4.772533e+05
55,60,البحر اليوسفي_الفيوم,247492.890070,1.117079e+09,265971.00,"POLYGON ((302590.371 3235187.362, 303062.302 3...",5.327437e+05,9.776698e+05
56,62,ترعة سري باشا,285344.080271,4.608900e+08,109736.00,"POLYGON ((276004.137 3085665.058, 275982.388 3...",2.903954e+05,6.877148e+05
57,63,ترعة الشيخ جابر,148008.629916,6.495025e+08,154643.00,"POLYGON ((434827.953 3431481.326, 434813.067 3...",7.946007e+04,1.261491e+05
58,65,البحر اليوسفي,600629.783332,1.055013e+09,251194.00,"POLYGON ((302565.274 3231847.839, 302683.361 3...",4.735906e+05,7.213953e+05
59,77,ترعة الجيزة,353243.598171,6.138948e+08,146165.00,"POLYGON ((312972.602 3344599.415, 313054.799 3...",8.063370e+05,9.193221e+05

In [45]:
excel_canal_drain_df = pd.DataFrame(
    {
        "area": com_gdf_ecrs["Name"],
        "drain_length": com_gdf_ecrs["drain_length"],
        "canal_length": com_gdf_ecrs["canal_length"],
    }
)

write_excel_file(excel_canal_drain_df, excel_path, sheet_name="canal_and_drain_length")

In [36]:
drains_gdf.crs

<Projected CRS: EPSG:32636>
Name: WGS 84 / UTM zone 36N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Between 30°E and 36°E, northern hemisphere between equator and 84°N, onshore and offshore. Belarus. Cyprus. Egypt. Ethiopia. Finland. Israel. Jordan. Kenya. Lebanon. Moldova. Norway. Russian Federation. Saudi Arabia. Sudan. Syria. Türkiye (Turkey). Uganda. Ukraine.
- bounds: (30.0, 0.0, 36.0, 84.0)
Coordinate Operation:
- name: UTM zone 36N
- method: Transverse Mercator
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [46]:
precipation_files = [
    src_dir / "egypt_annual_precipitation.tif",
    src_dir / "Egypt_annual_potentialevapotransporation.tif",
]

precipation_df = pd.DataFrame(
    {
        "area": com_gdf["Name"]
    }
)

for precipation_file in precipation_files:
    col = livestock_file.stem
    precipation_type = col.split("_")[-1]
    with rasterio.open(precipation_file) as precipation_src:
        stats = zonal_stats(
            com_gdf,
            precipation_file,
            affine=precipation_src.transform,
            stats=["sum"],
            nodata=precipation_src.nodata,
        )

    precipation_df[precipation_type] = [s["sum"] for s in stats]

write_excel_file(precipation_df, excel_path, sheet_name="precipation")

In [59]:
field_type_file = src_dir / "dominant_field_size_categories.tif"

gov_gdf = gpd.read_file(src_dir / 'Governorates.shp')
gov_gdf = gov_gdf.to_crs("EPSG:4326")

gov_field_stats = read_field_sizes(field_type_file, gov_gdf)

gov_field_size_df = create_stats_df(stats=gov_field_stats, area_gdf=gov_gdf)
gov_field_size_df['fraction_arable'] = 1 - gov_field_size_df['nr_no_field'] / gov_field_size_df['nr_of_fields'] 

# write_excel_file(field_size_df, excel_path, sheet_name="field_sizes")

In [60]:
gov_field_size_df

,area,nr_of_fields,nr_no_field,nr_<0.64ha,nr_0.64-2.56ha,nr_2.56-16ha,nr_16-100ha,nr_>100ha,fraction_arable
0,New Valley/El-Wadi El-Gidid,1369336,1354379,14433,524,0,0,0,0.010923
1,Matrouh,514175,504434,1336,2890,2318,3197,0,0.018945
2,Giza,123456,114866,7159,1431,0,0,0,0.069579
3,Beni-Suef,35541,29362,5633,546,0,0,0,0.173856
4,Menia,95553,84374,11179,0,0,0,0,0.116993
5,Behera,37138,9003,11412,14741,1982,0,0,0.757580
6,Fayoum,5674,356,5318,0,0,0,0,0.937258
7,Assyout,50770,44198,6572,0,0,0,0,0.129447
8,Cairo,10103,9460,643,0,0,0,0,0.063644
9,Alexandria,10348,4624,5357,367,0,0,0,0.553150
10,Kafr-El-Sheikh,10607,298,10309,0,0,0,0,0.971905
11,Menoufia,6373,129,5413,831,0,0,0,0.979758
12,Kalyoubia,3762,366,3396,0,0,0,0,0.902711
13,Gharbia,6520,52,6443,25,0,0,0,0.992025
14,Dakahlia,11348,241,11107,0,0,0,0,0.978763
15,Aswan,129420,124003,267,5150,0,0,0,0.041856
16,Red Sea,373308,373259,39,10,0,0,0,0.000131
17,Suhag,32035,26114,5921,0,0,0,0,0.184829
18,Quena,42057,35478,6579,0,0,0,0,0.156431
19,Luxor,737,10,727,0,0,0,0,0.986431
20,South Sinai,93341,93216,1,68,56,0,0,0.001339
21,Sharkia,16614,1231,14733,650,0,0,0,0.925906
22,Suez,29806,28748,0,1058,0,0,0,0.035496
23,Ismailia,16008,9725,1840,4402,41,0,0,0.392491
24,Damietta,2420,466,1954,0,0,0,0,0.807438
25,North Sinai,88790,84850,0,3344,596,0,0,0.044374
26,Port-Said,3802,1591,52,2159,0,0,0,0.581536

In [53]:
with rasterio.open(field_type_file) as src:

    transform, width, height = calculate_default_transform(
        src.crs,
        "EPSG:32636",
        src.width,
        src.height,
        *src.bounds,
    )

    data = np.empty((height, width), dtype=src.dtypes[0])

    reproject(
        source=rasterio.band(src, 1),
        destination=data,
        src_transform=src.transform,
        src_crs=src.crs,
        dst_transform=transform,
        dst_crs="EPSG:32636",
        resampling=Resampling.nearest,
    )

pixel_area_km2 = transform.a * abs(transform.e) / 1e6
# area_class_1 = np.sum(data == 1) * pixel_area_km2

In [54]:
pixel_area_km2

0.14742656584740893

In [56]:
(field_size_df['nr_of_fields'] - field_size_df['nr_no_field']) * pixel_area_km2

0      178.828424
1      661.945281
2      112.633896
3      894.436975
4      280.847608
5      341.734780
6      208.313738
7      330.530361
8       76.514388
9       30.517299
10     272.296867
11     285.270405
12     271.412308
13     619.191577
14     877.777773
15     577.027579
16      79.757772
17     146.984286
18     102.903743
19      20.344866
20      27.273915
21      70.764752
22     109.095659
23      47.913634
24       5.602210
25     235.587652
26      85.212555
27       8.845594
28     867.457913
29     469.406186
30     425.915349
31      23.735677
32     125.754861
33     141.234650
34     399.673420
35     684.648972
36     192.096815
37     161.432090
38     108.063673
39      85.065128
40     150.964803
41     493.141863
42     711.775460
43     246.054938
44     165.117754
45     110.569924
46     136.959280
47    1136.069116
48     570.098530
49     517.762099
50     252.541707
51     105.115141
52     338.933675
53    1224.819909
54     341.292500
55     524.248868
56     214.210800
57     222.024408
58     491.520171
59     275.097972
dtype: float64